Vagrant.configure("2") do |config|
config.vm.define :servidorUbuntu do |servidorUbuntu|
servidorUbuntu.vm.box = "bento/ubuntu-20.04"
servidorUbuntu.vm.box_version = "202012.21.0"
servidorUbuntu.vm.network :private_network, ip: "192.168.100.2"
servidorUbuntu.vm.provision "shell", path: "script.sh"
servidorUbuntu.vm.hostname = "servidorUbuntu"
end
end
